version: '3.9'

services:
  bid-db:
    image: postgres:15
    container_name: bid-db
    environment:
      POSTGRES_DB: bid_db
      POSTGRES_USER: postgres1
      POSTGRES_PASSWORD: 123tryitout1
    ports:
      - "5433:5432"
    volumes:
      - bid-db-data:/var/lib/postgresql/data

volumes:
  bid-db-data:

